[workspace]
members = [
  "abi",
  "acpi",
  "appkit",
  "karch",
  "boot",
  "core",
  "drivers",
  "font",
  "fs",
  "gfx",
  "kernel",
  "kernel-services",
  "mm",
  "net",
  "service-core",
  "utils",
  "sync",
  "ktesting",
  "slibc",
  "userland",
  "video",
  "windowing",
  "slop-protocol",
  "slopos-alloc",
  "slopos-ostd",
  "hermetic"
]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "GPL-3.0-only"

[workspace.lints.rust]
warnings = "deny"
non_camel_case_types = "deny"
non_snake_case = "deny"
non_upper_case_globals = "deny"

[workspace.lints.clippy]
type_complexity = "warn"
non_camel_case_types = "deny"

[workspace.dependencies]
bitflags = { version = "2.4", default-features = false }
libm = { version = "0.2", default-features = false }
limine = { version = "0.6.3", default-features = false }
slopos-arch = { path = "karch" }
slopos-abi = { path = "abi" }
slopos-acpi = { path = "acpi" }
slopos-appkit = { path = "appkit" }
slopos-boot = { path = "boot" }
slopos-core = { path = "core" }
slopos-drivers = { path = "drivers" }
slopos-font = { path = "font" }
slopos-fs = { path = "fs" }
slopos-gfx = { path = "gfx" }
slopos-alloc = { path = "slopos-alloc" }
slopos-ostd = { path = "slopos-ostd" }
  slopos-utils = { path = "utils" }
  slopos-testing = { path = "ktesting" }
  slopos-kernel-services = { path = "kernel-services" }
slopos-sync = { path = "sync" }
slopos-mm = { path = "mm" }
slopos-net = { path = "net" }
slopos-slibc = { path = "slibc" }
slopos-userland = { path = "userland" }
slopos-protocol = { path = "slop-protocol" }
slopos-video = { path = "video" }
slopos-windowing = { path = "windowing" }
slopos-hermetic = { path = "hermetic" }
paste = { version = "1.0", default-features = false }
x86_64 = { version = "0.15.4", default-features = false, features = ["instructions"] }
