[package]
name = "slopos-kernel-services"
version = "0.1.0"
edition = "2021"
license.workspace = true

[lib]
test = false
doctest = false

[dependencies]
slopos-service-core = { path = "../service-core" }
slopos-arch = { path = "../karch" }
slopos-abi = { path = "../abi" }
slopos-ostd = { path = "../slopos-ostd" }

[lints]
workspace = true
