[package]
name = "slopos-font"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

doctest = false

[dependencies]
slopos-abi = { workspace = true }
slopos-gfx = { workspace = true }
libm = { workspace = true }
