#![allow(dead_code, unused_imports)]

//! Regression tests for the TTY subsystem.
//!
//! Tests the `LineDisc`, `TtyDriverKind`, `TtyIndex`, TTY table, and
//! the per-TTY public API (compositor focus, foreground pgrp, active TTY).
//!
//! Coverage includes input flag processing, output processing, signal
//! generation, flow control, VLNEXT, VWERASE, ECHOCTL, compositor focus /
//! fg_pgrp split, check_read() as sole read gate, TtyIndex type safety,
//! and signal constant verification.

extern crate alloc;

use alloc::boxed::Box;

use slopos_abi::signal::{SIGCONT, SIGHUP, SIGINT, SIGQUIT, SIGTSTP, SIGTTIN, SIGTTOU, SIGWINCH};
use slopos_abi::syscall::{
    CcIndex, ControlFlags, InputFlags, LocalFlags, OutputFlags, POSIX_VDISABLE,
};
use slopos_lib::klog_info;
use slopos_lib::testing::TestResult;

use crate::tty;
use crate::tty::TtyError;
use crate::tty::TtyIndex;
use crate::tty::driver::{DriverId, TtyDriverKind, VConsoleDriver};
use crate::tty::ldisc::{InputAction, LdiscKind, LdiscOps, LineDisc, OutputAction, RawDisc};
use crate::tty::ringbuf::RingBuf;
use crate::tty::session::TtySession;
use crate::tty::session::{
    ForegroundCheck, NO_FOREGROUND_PGRP, NO_SESSION, ProcessGroupId, SessionId,
};
use crate::tty::table::{TTY_GENERATIONS, TTY_OUTPUT_INFLIGHT, TTY_SLOTS};
use crate::tty::vconsole::{
    Cell, CellAttributes, CellGrid, CursorAttributes, VCONSOLE_MAX_COLS, VCONSOLE_MAX_ROWS,
    VConsoleState,
};
use crate::tty::vtparser::{Direction, EraseMode, SgrAttr, VtAction, VtParser};

use crate::tty::pty::PtyPeerHandle;

pub(crate) fn boxed_vconsole_state() -> Box<VConsoleState> {
    let mut state = Box::<VConsoleState>::new_uninit();
    unsafe {
        let state_ref = state.as_mut_ptr();
        let _default_cell = CellAttributes {
            fg: 0x00AAAAAA,
            bg: 0x00000000,
        };
        let default_cursor = CursorAttributes {
            fg: 0x00AAAAAA,
            bg: 0x00000000,
            bold: false,
            underline: false,
            inverse: false,
        };
        (*state_ref).cursor_row = 0;
        (*state_ref).cursor_col = 0;
        (*state_ref).rows = 25;
        (*state_ref).cols = 80;
        (*state_ref).fb = None;
        core::ptr::write(&mut (*state_ref).cells, CellGrid::empty());
        (*state_ref)
            .cells
            .allocate(VCONSOLE_MAX_ROWS, VCONSOLE_MAX_COLS);
        (*state_ref).parser = VtParser::new();
        (*state_ref).cursor_attrs = default_cursor;
        (*state_ref).saved_cursor_row = 0;
        (*state_ref).saved_cursor_col = 0;
        (*state_ref).saved_cursor_attrs = default_cursor;
        (*state_ref).cursor_visible = true;
        core::ptr::write(&mut (*state_ref).alt_cells, CellGrid::empty());
        (*state_ref)
            .alt_cells
            .allocate(VCONSOLE_MAX_ROWS, VCONSOLE_MAX_COLS);
        (*state_ref).alt_screen_cursor_row = 0;
        (*state_ref).alt_screen_cursor_col = 0;
        (*state_ref).in_alt_screen = false;
        (*state_ref).scroll_top = 0;
        (*state_ref).scroll_bottom = 0;
        state.assume_init()
    }
}

pub(crate) fn drain_tty_nonblock(idx: TtyIndex) {
    let mut scratch = [0u8; 64];
    loop {
        match tty::read(idx, &mut scratch, true) {
            Ok(0) | Err(_) => break,
            Ok(_) => continue,
        }
    }
}

pub mod test_driver;
pub mod test_integration;
pub mod test_ioctls;
pub mod test_ldisc;
pub mod test_poll;
pub mod test_pty;
pub mod test_rawdisc;
pub mod test_ringbuf;
pub mod test_session;
pub mod test_table;
pub mod test_vconsole;

pub use test_driver::*;
pub use test_integration::*;
pub use test_ioctls::*;
pub use test_ldisc::*;
pub use test_poll::*;
pub use test_pty::*;
pub use test_rawdisc::*;
pub use test_ringbuf::*;
pub use test_session::*;
pub use test_table::*;
pub use test_vconsole::*;

slopos_lib::define_test_suite!(
    tty,
    [
        test_ringbuf_new_is_empty,
        test_ringbuf_push_pop,
        test_ringbuf_full_returns_false,
        test_ringbuf_peek_does_not_consume,
        test_ringbuf_peek_at_offset,
        test_ringbuf_read_bulk,
        test_ringbuf_read_partial,
        test_ringbuf_flush_resets,
        test_ringbuf_wraparound,
        test_ringbuf_capacity_and_free,
        test_pty_data_roundtrip,
        test_pty_hangup_propagation,
        test_errno_background_maps_to_eio,
        test_ldisc_ringbuf_integration,
        test_echo_batching_correctness,
        test_ldisc_new_has_no_data,
        test_ldisc_read_empty,
        test_ldisc_canonical_newline,
        test_ldisc_canonical_backspace,
        test_ldisc_canonical_kill,
        test_ldisc_canonical_eof,
        test_ldisc_signal_ctrl_c,
        test_ldisc_raw_mode,
        test_ldisc_set_termios_flush,
        test_ldisc_flush_all,
        test_ldisc_echo_printable,
        test_ldisc_echo_newline,
        test_ldisc_multiple_reads,
        test_ldisc_backspace_empty,
        test_session_new_empty,
        test_session_attach,
        test_session_detach,
        test_session_check_read_foreground,
        test_session_check_read_background,
        test_session_check_read_no_session,
        test_session_check_read_kernel_task,
        test_session_check_write_no_tostop,
        test_session_check_write_tostop_background,
        // check_read replaces task_has_access
        test_session_check_read_replaces_task_has_access_foreground,
        test_session_check_read_replaces_task_has_access_background,
        test_session_check_read_replaces_task_has_access_permissive,
        test_session_set_fg_pgrp_checked_allowed,
        test_session_set_fg_pgrp_checked_denied,
        test_session_set_fg_pgrp_checked_no_session,
        test_tty_get_session_id_default,
        test_tty_attach_session,
        test_tty_detach_session,
        test_tty_detach_session_by_id,
        test_tty_set_fg_pgrp_checked,
        test_tty_index_eq,
        test_driver_none_no_panic,
        test_vconsole_drain_returns_zero,
        test_table_init_allocates_tty0_and_tty1,
        test_table_tty0_has_index_zero,
        test_table_tty0_active,
        test_table_with_tty_exists,
        test_table_with_tty_empty,
        test_active_tty_default,
        test_set_active_tty,
        test_foreground_pgrp,
        test_compositor_focus,
        test_keyboard_enter_scancode_reaches_active_tty,
        test_keyboard_scancode_routes_to_active_tty_index,
        test_keyboard_extended_up_arrow_reaches_tty,
        // Input flag processing
        test_ldisc_icrnl,
        test_ldisc_igncr,
        test_ldisc_inlcr,
        test_ldisc_istrip,
        // Output processing
        test_ldisc_opost_onlcr,
        test_ldisc_opost_ocrnl,
        test_ldisc_output_raw,
        // Signal generation
        test_ldisc_signal_ctrl_backslash,
        test_ldisc_signal_ctrl_z,
        // Flow control
        test_ldisc_flow_control_ixon,
        // ECHOCTL
        test_ldisc_echoctl,
        // VLNEXT
        test_ldisc_vlnext,
        // VWERASE
        test_ldisc_vwerase,
        // edit_content / reprint
        test_ldisc_edit_content,
        // Output processing via TTY write
        test_tty_write_returns_input_len,
        // Input pipeline cleanup
        test_keyboard_no_input_event_delivery,
        test_keyboard_break_code_no_input,
        test_keyboard_modifier_no_input,
        test_keyboard_press_release_single_char,
        test_vconsole_drain_via_drain_hw_input,
        test_keyboard_multi_key_sequence,
        // FD integration
        test_tty_write_output_processing,
        test_tty_write_raw_passthrough,
        test_tty_write_invalid_index,
        test_tty_per_tty_termios_isolation,
        test_tty_per_tty_winsize_isolation,
        test_tty_per_tty_fg_pgrp_isolation,
        test_tty_per_tty_has_data_isolation,
        test_tty_per_tty_session_isolation,
        test_tty_read_invalid_tty_returns_error,
        // Control-Plane Correctness
        test_tty_index_abi_type,
        test_signal_constants,
        test_set_compositor_focus_does_not_set_fg_pgrp,
        test_check_read_sole_gate_background,
        test_tty_open_count_lifecycle,
        test_tty_hangup_sets_flag_and_detaches_session,
        test_tty_hangup_nonblock_read_eio,
        test_tty_hangup_blocking_read_eof,
        test_tty_error_variants,
        test_read_returns_result,
        test_read_invalid_index_error,
        test_read_not_allocated_error,
        test_write_returns_result,
        test_get_termios_returns_result,
        test_vmin0_vtime0_immediate_return,
        test_vmin0_vtime0_with_data_immediate_return,
        test_vmin_enforcement,
        test_vmin_limited_by_buffer_size,
        test_canonical_to_noncanonical_preserves_buffered_data,
        test_set_fg_pgrp_checked_permission_denied,
        test_hangup_read_returns_hung_up,
        // Per-TTY Locking & Performance
        test_per_tty_lock_independence,
        test_driver_id_round_trip,
        test_split_write_returns_input_len,
        test_idle_cb_iterates_all_ttys,
        test_merged_drain_read,
        test_with_tty_per_slot,
        test_driver_id_traits,
        // Job Control Correctness
        test_sigttou_constant,
        test_check_write_tostop_blocks_background,
        test_check_write_no_tostop_allows_background,
        test_check_write_tostop_allows_foreground,
        test_check_read_cross_session_rejected,
        test_check_read_same_session_foreground,
        test_check_read_kernel_task_allowed,
        test_tty_write_foreground_with_tostop,
        // Non-Canonical Timing Fix
        test_vmin_vtime_enough_data_returns_immediately,
        test_vmin_vtime_partial_nonblock,
        test_vmin_vtime_no_data_nonblock,
        test_vmin_vtime_interbyte_timeout_returns_partial,
        test_ldisc_vmin_vtime_helper,
        // Sane Defaults & Output Column Tracking
        test_default_termios_has_icrnl,
        test_default_termios_has_opost_onlcr,
        test_default_termios_has_full_lflag,
        test_output_column_tracking_printable,
        test_output_column_tracking_newline,
        test_output_column_tracking_cr,
        test_output_column_tracking_tab,
        test_output_column_tracking_backspace,
        test_onocr_at_column_zero,
        test_default_onlcr_newline_expands,
        // ABI Signal Constant Unification
        test_signal_values_from_signal_module,
        test_ldisc_signal_uses_signal_module,
        test_hangup_signals_from_signal_module,
        test_job_control_signals_from_signal_module,
        // Responsibility Split — PTY Foundation
        test_session_id_zero_is_none,
        test_session_id_round_trip,
        test_pgrp_id_zero_is_none,
        test_pgrp_id_round_trip,
        test_session_option_fields,
        test_session_option_attach_detach,
        test_raw_disc_new_empty,
        test_raw_disc_input_read,
        test_raw_disc_output_passthrough,
        test_raw_disc_flush,
        test_ldisc_kind_ntty_delegation,
        test_ldisc_kind_raw_delegation,
        test_pty_driver_id_variants,
        test_pty_master_driver_kind,
        test_pty_slave_driver_kind,
        // POSIX Quick Wins
        test_canonical_one_line_per_read,
        test_canonical_has_data_line_count,
        test_canonical_eof_line_boundary,
        test_sigwinch_constant,
        test_word_erase_path_boundary,
        test_word_erase_mixed_boundary,
        test_word_erase_trailing_spaces,
        test_canonical_small_buffer_read,
        test_tcsetsw_preserves_pending_input,
        test_tcsetsf_flushes_pending_input,
        test_read_with_attach_false_skips_auto_attach,
        test_read_with_attach_true_skips_durable_attach,
        test_acquire_and_release_controlling_terminal,
        test_release_wrong_session_is_noop,
        test_get_ldisc_default_is_ntty,
        test_set_ldisc_round_trip_preserves_termios,
        test_set_ldisc_invalid_id_rejected,
        test_pty_alloc_returns_master_and_slave,
        test_pty_master_to_slave_flow,
        test_pty_slave_to_master_flow,
        test_master_close_hangs_up_slave,
        test_slave_close_returns_master_eof,
        test_pty_canonical_editing_on_slave,
        // Strict Session Gates & Foreground Outcomes
        test_bootstrap_allowed_no_session_read,
        test_bootstrap_allowed_no_fg_pgrp,
        test_denied_cross_session_read,
        test_denied_cross_session_write_tostop,
        test_cross_session_write_no_tostop_still_denied,
        test_kernel_task_exempted_cross_session_read,
        test_kernel_task_exempted_cross_session_write,
        test_same_session_background_read_sigttin,
        test_same_session_background_write_sigttou,
        test_check_write_no_session_allowed,
        test_cross_session_denied_error_variant,
        // PTY Pair Atomicity & Lifecycle Hardening
        test_pty_alloc_pair_both_initialized,
        test_pty_close_master_first_frees_pair,
        test_pty_close_slave_first_frees_pair,
        test_pty_reallocation_after_free,
        test_pty_open_slave_validates_type,
        test_pty_open_slave_prevents_free,
        test_partial_open_no_free,
        test_rapid_alloc_free_realloc,
        test_pty_open_slave_after_free,
        // Event-Driven Readiness & IXON Completion
        test_poll_events_pollin_with_data,
        test_poll_events_no_pollin_without_data,
        test_poll_events_pollout_when_not_stopped,
        test_poll_events_no_pollout_when_stopped,
        test_poll_events_pollhup_on_hangup,
        test_poll_events_invalid_index_returns_zero,
        test_ixon_stopped_state_via_push_input,
        test_ixon_any_char_resumes,
        test_poll_events_respects_requested_mask,
        test_pollhup_always_reported,
        test_poll_events_peer_closed_pollhup,
        test_default_console_tty_initial_value,
        test_set_default_console_tty,
        test_switch_active_tty_valid,
        test_switch_active_tty_invalid_index,
        test_switch_active_tty_unallocated,
        test_vconsole_state_initial,
        test_vconsole_write_byte_printable,
        test_vconsole_write_byte_newline,
        test_vconsole_write_byte_cr,
        test_vconsole_write_byte_backspace,
        test_vconsole_scroll_at_bottom,
        test_active_tty_independent_of_fg_pgrp,
        test_vconsole_has_framebuffer_default_false,
        // Canonical EOF, ISIG Flush & Signal Integrity
        test_canonical_eof_empty_no_phantom,
        test_canonical_eof_with_pending_text_no_phantom,
        test_isig_flush_no_noflsh,
        test_isig_flush_with_noflsh,
        test_isig_ctrl_c_clears_edit_buffer,
        test_isig_flush_sigquit,
        test_isig_flush_sigtstp,
        test_double_eof_no_phantom_accumulation,
        // Job Control & Controlling TTY Hardening
        test_set_fg_pgrp_checked_nonexistent_pgrp,
        test_set_fg_pgrp_checked_clear_allowed,
        test_set_fg_pgrp_checked_no_session_skips_validation,
        test_detach_ctty_non_leader,
        test_detach_ctty_session_leader,
        test_detach_ctty_cross_session_denied,
        test_tiocnotty_constant,
        // Real TCSETSW/TCSETSF Drain Semantics
        test_is_output_idle_initially_true,
        test_inflight_counter_initial_zero,
        test_write_updates_inflight_counter,
        test_tcsetsw_preserves_input_after_drain,
        test_tcsetsf_flushes_input_after_drain,
        test_is_output_idle_invalid_index,
        test_is_output_idle_unallocated,
        test_drain_invalid_index_error,
        test_driver_output_pending_default_false,
        test_driver_kind_output_pending_dispatch,
        test_pty_output_idle_immediate,
        test_console_drain_immediate,
        test_tcsets_now_skips_drain,
        // PTY Lifetime Safety & Scalable Capacity
        test_max_ttys_is_32,
        test_pty_peer_handle_creation,
        test_pty_peer_handle_snapshot,
        test_generation_bumped_on_free,
        test_stale_handle_detected,
        test_pty_alloc_captures_generation,
        test_stale_write_safe_noop,
        test_rapid_alloc_free_stress,
        test_data_flow_with_generation,
        test_validate_peer_out_of_range,
        test_multiple_pty_pairs,
        // POSIX Completion Set (Rust-Idiomatic)
        test_ignbrk_discards_break,
        test_brkint_generates_sigint,
        test_parmrk_inserts_marker,
        test_nul_without_break_flags_passes_through,
        test_echoke_visual_erase,
        test_echok_newline_on_kill,
        test_echoctl_erase_two_columns,
        test_bytes_available,
        test_raw_disc_bytes_available,
        test_ldisc_kind_bytes_available,
        test_fionread_constant,
        test_kill_empty_line_no_echo,
        test_ignbrk_takes_priority_over_brkint,
        // Type-Safe Termios Foundation
        test_input_flags_from_bits,
        test_output_flags_from_bits,
        test_local_flags_from_bits,
        test_cc_index_values,
        test_posix_vdisable,
        test_tty_error_to_errno,
        test_tty_error_signal_interrupt,
        test_user_termios_typed_accessors,
        test_ldisc_typed_flags_behavioral_equivalence,
        test_control_flags_empty,
        // LdiscKind Dispatch Consolidation
        test_from_id_still_works,
        test_ldisc_ops_linedisc_trait_delegation,
        test_ldisc_ops_rawdisc_trait_delegation,
        test_dispatch_macro_ntty_routing,
        test_dispatch_macro_raw_routing,
        test_process_output_byte_dispatch,
        test_edit_content_dispatch,
        // /dev/tty Controlling Terminal Device
        test_open_ref_second_fd_increments_count,
        test_dev_tty_operations_identical_to_direct,
        test_open_ref_does_not_modify_session,
        test_open_ref_invalid_index_returns_error,
        test_close_ref_decrements_after_open,
        test_multiple_open_ref_sequential,
        test_dev_tty_winsize_matches_direct,
        // Background Write Protection (SIGTTOU on tcsetattr)
        test_tcsetattr_background_blocked,
        test_tcsetattr_foreground_allowed,
        test_tcsetattr_no_session_allowed,
        test_tcsetattr_cross_session_denied,
        test_orphaned_pgrp_errno,
        test_tcsetattr_kernel_task_bypass,
        test_tcsetsw_tcsetsf_kernel_task_bypass,
        test_tostop_background_write_check,
        test_kernel_task_check_write_allowed,
        // Controlling Terminal Lifecycle Integrity
        test_acquire_ctty_fresh_tty,
        test_acquire_ctty_same_session_idempotent,
        test_acquire_ctty_different_session_denied,
        test_release_ctty_owning_session,
        test_release_ctty_wrong_session_noop,
        test_hangup_detaches_session,
        test_o_noctty_suppresses_acquire,
        test_detach_ctty_non_leader_preserves_session,
        test_detach_ctty_session_leader_detaches,
        test_full_lifecycle_acquire_release_reacquire,
        test_double_acquire_race_guard,
        test_hangup_no_session_safe,
        test_rapid_acquire_release_stress,
        test_acquire_invalid_index,
        test_release_invalid_index,
        test_detach_invalid_index,
        // Post-Hangup I/O Hardening
        test_hangup_read_returns_eof,
        test_hangup_write_returns_eio,
        test_hangup_poll_returns_pollhup_pollin,
        test_hangup_set_termios_returns_eio,
        test_hangup_set_winsize_returns_eio,
        test_hangup_set_ldisc_returns_eio,
        test_hangup_get_fg_pgrp_still_works,
        test_pty_master_close_slave_eof_eio,
        test_hangup_permanent_eof,
        test_pty_slave_poll_pollhup_after_master_close,
        test_hungup_errno_is_eio,
        // Extended Line Boundaries (VEOL, VEOL2)
        test_veol_completes_line,
        test_veol2_completes_line,
        test_veol_disabled_no_effect,
        test_veol_and_newline_coexist,
        test_veol_echo_behavior,
        test_veol_no_echo,
        test_veol2_cc_index,
        test_veol_veol2_both_active,
        test_veol_and_eof_coexist,
        // UTF-8 Aware Editing (IUTF8)
        test_utf8_char_width,
        test_iutf8_backspace_ascii,
        test_iutf8_backspace_2byte,
        test_iutf8_backspace_3byte_cjk,
        test_iutf8_backspace_4byte_emoji,
        test_no_iutf8_backspace_multibyte,
        test_iutf8_insert_column_tracking,
        test_iutf8_word_erase_mixed,
        test_iutf8_word_erase_preserves_prefix,
        test_iutf8_flag_value,
        // Input Buffer Policy (IMAXBEL, IXOFF, CREAD)
        test_cread_enabled_input_processed,
        test_cread_disabled_input_discarded,
        test_cread_disabled_rawdisc,
        test_imaxbel_buffer_full_rings_bell,
        test_imaxbel_not_set_buffer_full_silent,
        test_imaxbel_buffer_not_full_normal,
        test_imaxbel_raw_mode_buffer_full,
        test_ixoff_high_water_sends_xoff,
        test_ixoff_low_water_sends_xon,
        test_ixoff_not_set_no_flow_control,
        test_cread_flag_value,
        test_imaxbel_flag_value,
        // Deferred Reprint (PENDIN)
        test_pendin_flag_value,
        test_pendin_auto_set_on_echo_change,
        test_pendin_one_shot,
        test_vreprint_clears_pendin,
        test_pendin_not_set_for_non_echo_flags,
        test_pendin_empty_edit_buffer,
        test_flush_clears_pendin,
        test_flush_input_clears_pendin,
        // PTY Namespace & Device Nodes
        test_pty_lock_ioctl_constants,
        test_slave_locked_by_default,
        test_locked_slave_open_rejected,
        test_unlock_enables_open,
        test_get_lock_round_trip,
        test_set_lock_non_master_rejected,
        test_data_flow_after_unlock,
        test_master_close_slave_hangup,
        test_multiple_pairs_with_locks,
        test_non_pty_not_locked,
        test_get_lock_non_master_error,
        // PTY Packet Mode (TIOCPKT)
        test_abi_constants,
        test_tiocpkt_on_data_prefixed,
        test_tiocpkt_off_normal_read,
        test_tiocpkt_slave_flush_read,
        test_tiocpkt_ixon_toggle,
        test_tiocpkt_disable_clears_events,
        test_poll_packet_events_pollin,
        test_set_packet_mode_non_master,
        // VT100/ANSI Terminal Emulation
        test_parser_print_ascii,
        test_parser_execute_control,
        test_clear_screen,
        test_cursor_position,
        test_sgr_red_foreground,
        test_sgr_reset,
        test_cursor_up,
        test_malformed_sequence_resilience,
        test_sgr_multi_param,
        test_vconsole_clear_screen,
        test_vconsole_cursor_pos,
        test_vconsole_sgr_color,
        test_vconsole_sgr_reset,
        test_vconsole_save_restore_cursor,
        test_parser_fuzz_no_panic,
        test_vconsole_erase_line,
        test_cursor_movement_clamping,
        test_vconsole_scroll_up,
        // Advanced PTY & Session Control (EXTPROC, vhangup)
        test_extproc_flag_value,
        test_extproc_no_echo,
        test_extproc_no_canonical_editing,
        test_extproc_signals_still_delivered,
        test_extproc_cleared_resumes_normal,
        test_extproc_bypasses_iexten_editing,
        test_extproc_flow_control_works,
        test_extproc_imaxbel,
        test_vhangup_syscall_constant,
        test_vhangup_triggers_hangup,
        test_extproc_raw_mode_same_behavior,
        // Legacy Termios Completion (ECHOPRT, IUCLC, OLCUC)
        test_echoprt_erase_format,
        test_echoprt_close_on_input,
        test_iuclc_maps_upper_to_lower,
        test_iuclc_no_effect_non_alpha,
        test_olcuc_maps_lower_to_upper,
        test_flags_disabled_by_default,
        // Per-TTY Poll Notification
        test_poll_waiters_exist,
        test_push_input_wakes_correct_poll_waiter,
        test_push_input_does_not_wake_other_slot,
        test_hangup_wakes_correct_poll_waiter,
        test_pty_packet_event_wakes_master_poll_waiter,
        test_poll_sleep_on_empty_slots_does_not_panic,
        // PTY Flow Control (Throttle Mechanism)
        test_throttle_watermark_constants,
        test_pty_initially_unthrottled,
        test_throttle_activates_at_high_water,
        test_master_write_short_write_when_throttled,
        test_read_unthrottles_slave,
        test_throttle_cycle_no_data_loss,
        test_console_not_throttled,
        test_master_write_full_when_not_throttled,
        // Cooked Buffer Overflow Hardening
        test_push_cooked_returns_false_when_full,
        test_push_cooked_returns_true_when_space,
        test_canonical_flush_fits_in_cooked,
        test_imaxbel_bell_on_cooked_overflow,
        test_no_imaxbel_silent_drop,
        // c_cflag ABI Completion
        test_control_flag_values,
        test_default_cflag,
        test_cflag_roundtrip,
        test_speed_fields_populated,
        test_speed_follows_baud_change,
        test_cread_value_preserved,
        // Missing Ioctls (TCFLSH, TCSBRK, TCXONC)
        test_flush_flow_ioctl_constants,
        test_tcflush_input,
        test_tcflush_output,
        test_tcflush_both,
        test_tcflush_invalid_arg,
        test_tcsbrk_noop,
        test_tcsbrk_drain,
        test_tcxonc_all_actions,
        // Edit Buffer Expansion (1024 → 4096)
        test_canonical_input_over_1024,
        test_large_paste_canonical,
        test_backspace_in_expanded_buffer,
        // Signal Restart Infrastructure (ERESTARTSYS)
        test_restart_error_to_errno,
        test_restart_distinct_from_signal_interrupt,
        test_erestartsys_constant_value,
        test_eintr_constant_value,
        test_sa_restart_flag_value,
        test_sa_restart_distinct,
        test_signal_interrupt_still_eintr,
        test_all_error_variants_preserved,
        test_nonblock_empty_returns_wouldblock,
        test_read_with_data_succeeds,
        // Review Fix Regression Tests
        test_review_tcflush_unthrottles_pty,
        test_review_tcflush_both_unthrottles_pty,
        test_review_master_write_batch_boundary,
        test_review_speed_fields_merge_into_cflag,
        test_review_speed_ispeed_fallback,
        test_review_speed_unrecognised_noop,
        test_review_pollerr_on_hangup,
        test_review_pollerr_on_peer_closed,
        // Bug-fix regression tests (TTY review)
        test_bugfix_flush_edit_preserves_remainder,
        test_bugfix_nonblock_write_throttled_pty,
        test_bugfix_nonblock_write_unthrottled_pty,
        test_bugfix_rawdisc_input_full,
        test_bugfix_slave_write_stops_on_full,
        test_bugfix_linedisc_input_full,
        // Bug-fix regression tests (TTY architectural review)
        test_bugfix_parmrk_atomic_full_insert,
        test_bugfix_parmrk_drop_when_insufficient_space,
        test_bugfix_parmrk_imaxbel_bell_on_insufficient_space,
        test_bugfix_parmrk_drop_when_buffer_completely_full,
        test_bugfix_tcxonc_invalid_action_returns_error,
        test_bugfix_tcxonc_boundary_values,
        // TCXONC Behavioral Completion
        test_tcooff_blocks_nonblock_write,
        test_tcoon_resumes_write,
        test_tcooff_idempotent,
        test_tcoon_idempotent,
        test_stop_resume_cycle,
        test_tcioff_tcion_succeed,
        test_tcioff_tcion_no_output_stop,
        test_invalid_action_still_errors,
        test_tcooff_pty_slave_write,
        test_output_stopped_independent_of_ixon,
        test_tcxonc_unallocated_slot,
        test_tcxonc_invalid_index,
        // Output Queue Visibility (TIOCOUTQ)
        test_tiocoutq_abi_constant,
        test_output_queued_zero_when_idle,
        test_output_queued_reflects_inflight,
        test_output_queued_zero_after_flush,
        test_output_queued_unallocated,
        test_output_queued_invalid_index,
        test_fionread_unchanged,
        test_output_queued_vconsole,
        // Input Wake Batching (WAKEUP_CHARS)
        test_wakeup_chars_constant,
        test_canonical_wake_on_newline,
        test_noncanonical_no_wake_per_byte,
        test_noncanonical_wake_at_threshold,
        test_noncanonical_wake_near_full,
        test_flush_input_resets_wake_counter,
        test_flush_all_resets_wake_counter,
        test_rawdisc_wake_batching,
        test_wake_resets_counter,
        test_canonical_eof_wakes,
        // TABDLY/XTABS Output Compatibility
        test_tabdly_abi_constants,
        test_default_oflag_includes_xtabs,
        test_xtabs_expands_tab_to_spaces,
        test_tab0_passes_literal_tab,
        test_tab0_column_tracking,
        test_xtabs_column_tracking_mixed,
        test_tabdly_termios_roundtrip,
        test_no_opost_tab_passthrough,
        test_existing_output_unaffected,
        // no_room-style Overflow Recovery
        test_no_room_initially_false,
        test_no_room_set_on_cooked_full,
        test_no_room_not_set_before_full,
        test_overflow_count_increments,
        test_overflow_count_saturates,
        test_no_room_clears_on_drain_below_threshold,
        test_no_room_stays_above_threshold,
        test_flush_input_clears_no_room,
        test_flush_all_clears_no_room,
        test_fill_drain_cycle_preserves_throttle,
        test_rawdisc_no_room,
        test_imaxbel_preserved_with_no_room,
        test_rawdisc_recovery,
        test_ldisc_kind_dispatch,
        // Output Drain Semantics Hardening
        test_drain_idle_fast_path,
        test_drain_hangup_vacuously_complete,
        test_tcsbrk_hangup_returns_error,
        test_tcsbrk_zero_hangup_returns_error,
        test_tcsbrk_zero_healthy_succeeds,
        test_tcsbrk_and_tcsetsw_share_drain,
        test_drain_invalid_index,
        test_drain_unallocated_slot,
        test_pty_tcsbrk_drain_immediate,
        test_console_drain_synchronous,
        test_output_pending_bytes_all_drivers,
        test_output_queued_uses_pending_bytes,
        test_tcsetsw_hangup_returns_error,
        test_tcsetsf_hangup_returns_error,
        test_inflight_accounting_round_trip,
        // Core Semantic Correctness (Gold Standard Audit)
        test_input_event_normal_behavior,
        test_input_event_break_brkint,
        test_input_event_break_ignbrk,
        test_input_event_parity_parmrk,
        test_input_event_parity_ignpar,
        test_input_event_overrun_noop,
        test_poll_output_stopped_masks_pollout,
        test_poll_output_not_stopped_has_pollout,
        test_grantpt_unlocks_slave,
        test_b0_hangup,
        test_speed_roundtrip,
        test_batched_ingress_no_data_loss,
        test_batched_ingress_signal_in_middle,
        test_background_read_sigttin_blocked_eio,
        test_receive_buf_accumulates_echo,
        // VConsole Unicode & Broadened Xterm Emulation
        test_utf8_2byte_renders_codepoint,
        test_utf8_3byte_renders_codepoint,
        test_utf8_4byte_renders_codepoint,
        test_utf8_invalid_byte_emits_replacement,
        test_utf8_truncated_sequence_emits_replacement,
        test_utf8_overlong_rejected,
        test_ascii_still_works,
        test_sgr_256_foreground,
        test_sgr_256_background,
        test_sgr_truecolor_foreground,
        test_sgr_truecolor_background,
        test_vconsole_256_color_sets_fg,
        test_vconsole_truecolor_sets_fg,
        test_bracketed_paste_enable_disable,
        test_decawm_default_on,
        test_decawm_toggle,
        test_decckm_toggle,
        test_decom_toggle,
        test_dectcem_still_works,
        test_alt_screen_still_works,
        test_cell_model_u32,
        test_vconsole_utf8_hello_renders,
        test_double_width_cjk,
        test_invalid_utf8_in_vconsole,
        test_mixed_ascii_utf8_escapes,
        test_256color_cube_mapping,
        test_256color_grayscale_mapping,
        test_is_double_width_ranges,
        test_sgr_standard_colors_unaffected,
        test_parser_fuzz_utf8_no_panic,
        test_vtparser_fuzz_no_panic,
        test_replacement_glyph_exists,
        test_get_glyph_for_codepoint_ascii,
        // mod.rs Module Decomposition
        test_mod_reexports_io_functions,
        test_mod_reexports_termios_functions,
        test_mod_reexports_job_control_functions,
        test_mod_reexports_lifecycle_functions,
        test_mod_reexports_poll_functions,
        test_mod_reexports_pty_functions,
        test_tty_struct_fields_accessible,
        test_tty_error_variants_unchanged,
        test_max_ttys_constant,
        test_existing_api_smoke_test,
        // POSIX Controlling Terminal Semantics
        test_ctty_can_be_ctty_serial,
        test_ctty_can_be_ctty_vconsole,
        test_ctty_can_be_ctty_pty_slave,
        test_ctty_cannot_be_ctty_pty_master,
        test_ctty_acquire_ctty_pty_master_rejected,
        test_ctty_acquire_ctty_pty_slave_succeeds,
        test_ctty_acquire_ctty_serial_console_succeeds,
        test_ctty_acquire_ctty_vconsole_succeeds,
        test_ctty_o_noctty_constant_value,
        test_ctty_set_fg_pgrp_completes_without_deadlock,
        test_ctty_set_fg_pgrp_checked_completes_without_deadlock,
        test_ctty_pty_master_ctty_does_not_attach_session,
        test_ctty_can_be_ctty_none_driver,
        // TIOCOUTQ Byte Accounting & Packet Mode Edge Fix
        test_inflight_byte_granularity,
        test_tiocoutq_returns_bytes_not_ops,
        test_tiocoutq_zero_after_sync_write,
        test_tiocoutq_various_byte_counts,
        test_packet_mode_1byte_with_events,
        test_packet_mode_1byte_data_no_events,
        test_packet_mode_1byte_no_data_nonblock,
        test_packet_mode_2byte_works,
        test_tiocoutq_byte_accounting_regression_idle,
        test_packet_mode_data_prefix_regression,
        test_echo_inflight_byte_granularity,
        // Missing Ioctls (TIOCGSID, TIOCEXCL) & HUPCL Enforcement
        test_excl_hupcl_tiocgsid_abi_constant,
        test_excl_hupcl_tiocexcl_abi_constants,
        test_excl_hupcl_errno_ebusy_value,
        test_excl_hupcl_get_session_id_returns_correct_sid,
        test_excl_hupcl_get_session_id_unallocated,
        test_excl_hupcl_exclusive_initially_false,
        test_excl_hupcl_set_exclusive_roundtrip,
        test_excl_hupcl_exclusive_blocks_second_open,
        test_excl_hupcl_nxcl_allows_second_open,
        test_excl_hupcl_exclusive_unallocated_slot,
        test_excl_hupcl_hupcl_last_close_triggers_hangup,
        test_excl_hupcl_no_hupcl_last_close_no_hangup,
        test_excl_hupcl_hupcl_pty_no_double_hangup,
        test_excl_hupcl_close_clears_exclusive,
        test_ttyflags_default_empty,
        test_ttyflags_insert_remove_contains,
        test_mark_hung_up_clears_output_stopped,
        test_packet_events_default_empty,
        test_packet_events_from_bits_matches_tiocpkt,
        test_packet_events_bits_roundtrip,
        test_tty_fields_pub_crate_smoke,
        test_session_fields_pub_crate_smoke,
        test_slave_starts_locked,
        test_ttyflags_set_method,
        test_ttyflags_multi_flag_operations,
        test_no_driver_kind_none,
        // Phase 21: Deferred Actions RAII & Boilerplate Reduction
        test_p21_postlockwork_default_is_empty,
        test_p21_postlockwork_signal_makes_nonempty,
        test_p21_postlockwork_execute_completes,
        test_p21_postlockwork_ixoff_byte,
        test_p21_postlockwork_packet_event,
        test_p21_postlockwork_packet_event_merge,
        test_p21_postlockwork_wake_helpers,
        test_p21_postlockwork_zero_pgid_signal_ignored,
        test_p21_postlockwork_zero_event_bits_ignored,
        test_p21_write_path_peer_cache_consolidation,
        test_p21_forward_ldisc_ops_linedisc,
        test_p21_forward_ldisc_ops_rawdisc,
        test_p21_existing_api_smoke_read_write,
    ]
);
