[package]
name = "slopos-arch"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
test = false
doctest = false

[dependencies]
bitflags.workspace = true
slopos-abi = { path = "../abi" }
slopos-ostd = { path = "../slopos-ostd" }
x86_64 = { version = "0.15.4", default-features = false, features = ["instructions"] }
