[package]
name = "slopos-testing"
version = "0.1.0"
edition = "2021"
license.workspace = true

[lib]
path = "src/lib.rs"
test = false
doctest = false

[features]
default = []
qemu-exit = []
test-hooks = []
tests = ["qemu-exit"]

[dependencies]
slopos-ostd = { workspace = true }
slopos-arch = { path = "../karch" }
slopos-kernel-services = { path = "../kernel-services" }
slopos-service-core = { path = "../service-core" }
