[package]
name = "kernel"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = []
tests = ["slopos-boot/tests", "slopos-fs/tests", "slopos-testing/tests", "test-hooks"]
test-hooks = ["slopos-boot/test-hooks"]
xe-gpu = ["slopos-boot/xe-gpu"]

[dependencies]
slopos-boot = { workspace = true }
slopos-core = { workspace = true }
slopos-drivers = { workspace = true }
slopos-fs = { workspace = true }
slopos-mm = { workspace = true }
slopos-testing = { workspace = true }
slopos-utils = { workspace = true }
slopos-video = { workspace = true }

[[bin]]
name = "kernel"
path = "src/main.rs"
test = false
