[package]
name = "slopos-mm"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

test = false
doctest = false
[features]
default = []
itests = []

[dependencies]
bitflags.workspace = true
slopos-abi = { workspace = true }
slopos-alloc = { workspace = true }
slopos-arch = { workspace = true }
slopos-testing = { workspace = true }
slopos-utils = { workspace = true }
slopos-sync = { workspace = true }
