[package]
name = "slopos-mm"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

test = false
doctest = false
[features]
default = []
test-hooks = []

[dependencies]
bitflags.workspace = true
slopos-abi = { workspace = true }
slopos-arch = { workspace = true }
slopos-kernel-services = { workspace = true }
slopos-ostd = { workspace = true }
slopos-testing = { workspace = true }
