/*
 * Rust Canvas FFI Test
 * Demonstrates the Rust graphics stack from C
 */

#include <stdint.h>
#include "../lib/klog.h"
#include "rust_graphics.h" // Generated by cbindgen, copied to builddir/rust/

void test_rust_canvas(void) {
    klog_printf(KLOG_INFO, "=== Rust Canvas FFI Test ===\n");

    // Create a display canvas
    RustCanvas *canvas = rust_canvas_create_display();
    if (!canvas) {
        klog_printf(KLOG_INFO, "Failed to create display canvas (no framebuffer)\n");
        return;
    }

    uint32_t width = rust_canvas_width(canvas);
    uint32_t height = rust_canvas_height(canvas);
    klog_printf(KLOG_INFO, "Canvas created: %ux%u\n", width, height);

    // Clear to dark gray
    rust_canvas_clear(canvas, rust_color_rgb(32, 32, 32));

    // Set fill color to red
    rust_canvas_set_fill_color(canvas, rust_color_rgb(255, 0, 0));

    // Draw filled rectangle
    rust_canvas_fill_rect(canvas, 50.0f, 50.0f, 200.0f, 100.0f);

    // Set stroke color to white
    rust_canvas_set_stroke_color(canvas, rust_color_rgb(255, 255, 255));
    rust_canvas_set_stroke_width(canvas, 2.0f);

    // Draw circle outline
    rust_canvas_stroke_circle(canvas, 400.0f, 200.0f, 80.0f);

    // Set fill color to blue
    rust_canvas_set_fill_color(canvas, rust_color_rgb(0, 0, 255));

    // Draw filled circle
    rust_canvas_fill_circle(canvas, 600.0f, 200.0f, 60.0f);

    // Test transforms
    rust_canvas_save(canvas);
    rust_canvas_translate(canvas, 400.0f, 400.0f);
    rust_canvas_rotate(canvas, 0.785f); // 45 degrees
    rust_canvas_set_fill_color(canvas, rust_color_rgb(0, 255, 0));
    rust_canvas_fill_rect(canvas, -50.0f, -50.0f, 100.0f, 100.0f);
    rust_canvas_restore(canvas);

    // Draw some lines
    rust_canvas_set_stroke_color(canvas, rust_color_rgb(255, 255, 0));
    rust_canvas_draw_line(canvas, 100.0f, 300.0f, 700.0f, 400.0f);

    klog_printf(KLOG_INFO, "Rust canvas test complete!\n");

    // Clean up
    rust_canvas_destroy(canvas);
}
