/*
 * SlopOS Rust FFI Test
 * Tests calling Rust graphics functions from C
 */

#include <stdint.h>
#include "../lib/klog.h"
#include "../boot/init.h"

/* Rust FFI function declarations (from graphics.h generated by cbindgen) */
extern uint32_t rust_graphics_test_add(uint32_t a, uint32_t b);
extern int32_t rust_graphics_init(void);
extern uint32_t rust_graphics_version(void);
extern void rust_graphics_test_log(uint32_t level, uint32_t should_panic);

static int test_rust_ffi_basic(void) {
    klog_info("Testing Rust FFI: basic function calls");

    // Test 1: Simple addition
    uint32_t result = rust_graphics_test_add(10, 32);
    klog_printf(KLOG_INFO, "Rust add(10, 32) = %u (expected 42)\n", result);

    if (result != 42) {
        klog_printf(KLOG_INFO, "ERROR: Rust FFI add test failed! Got %u, expected 42\n", result);
        return -1;
    }

    // Test 2: Get version
    uint32_t version = rust_graphics_version();
    klog_printf(KLOG_INFO, "Rust graphics version = %u\n", version);

    // Test 3: Initialize graphics
    int32_t init_result = rust_graphics_init();
    klog_printf(KLOG_INFO, "Rust graphics init = %d\n", init_result);

    // Test 4: Log function (without panic)
    klog_info("Calling Rust log function (should not panic)...");
    rust_graphics_test_log(KLOG_INFO, 0);
    klog_info("Rust log function completed successfully");

    klog_info("All Rust FFI tests PASSED!");
    return 0;
}

static int boot_step_rust_ffi_test(void) {
    klog_debug("Running Rust FFI integration test...");
    return test_rust_ffi_basic();
}

BOOT_INIT_STEP(optional, "rust ffi test", boot_step_rust_ffi_test);
