//! Outgoing TCP segments and their wire-format serializer.
//!
//! The state machine emits [`TcpOutSegment`] values describing *what* should
//! go on the wire; [`write_tcp_segment`] turns one into the actual bytes
//! (header + options + payload + checksum).  Splitting construction from
//! serialization keeps the state handlers free of byte-order plumbing and
//! gives tests one place to inspect either half.
//!
//! The [`SegmentBuilder`] type lands in P2.1 and is currently a thin stub;
//! state handlers still construct `TcpOutSegment { ... }` directly.

use super::TcpTuple;
use super::header::{
    DEFAULT_MSS, DEFAULT_WINDOW_SIZE, TCP_FLAG_ACK, TCP_FLAG_FIN, TCP_FLAG_PSH, TCP_FLAG_RST,
    TCP_FLAG_SYN, TCP_HEADER_LEN, TCP_OPT_END, TCP_OPT_MSS, TCP_OPT_MSS_LEN, TCP_OPT_NOP,
    TCP_OPT_WINDOW_SCALE, TCP_OPT_WINDOW_SCALE_LEN, TcpHeader, build_header, write_header,
};

/// Outgoing segment generated by the state machine.
///
/// The TCP layer produces these; the network layer converts them to
/// wire-format packets via [`write_tcp_segment`] and hands them to the NIC.
#[derive(Clone, Copy, Debug)]
pub struct TcpOutSegment {
    pub tuple: TcpTuple,
    pub seq_num: u32,
    pub ack_num: u32,
    pub flags: u8,
    pub window_size: u16,
    /// MSS option to include (0 = no MSS option).
    pub mss: u16,
    /// Window Scale option shift count (255 = don't include option).
    pub wscale: u8,
    /// Include SACK-Permitted option (SYN/SYN-ACK only).
    pub sack_permitted: bool,
    /// SACK blocks to include (left_edge, right_edge) pairs.
    pub sack_blocks: [(u32, u32); 4],
    /// Number of valid SACK blocks (0–4).
    pub sack_block_count: u8,
}

/// Serialize a [`TcpOutSegment`] plus its payload into `out`.
///
/// Writes the TCP header, MSS / Window Scale options (if requested), payload
/// bytes, and finally patches the checksum field (bytes 16..18) with the
/// one's-complement sum over the pseudo-header plus the whole segment.
///
/// Returns the number of bytes written or `None` if `out` is too short.
pub fn write_tcp_segment(seg: &TcpOutSegment, payload: &[u8], out: &mut [u8]) -> Option<usize> {
    use super::header::{TCP_OPT_SACK, TCP_OPT_SACK_PERMITTED, TCP_OPT_SACK_PERMITTED_LEN};

    let has_mss = seg.mss != 0;
    let has_wscale = seg.wscale != 255;
    let sack_n = seg.sack_block_count as usize;
    let mut opt_len = 0usize;
    if has_mss {
        opt_len += 4;
    }
    if has_wscale {
        // NOP + Window Scale (3 bytes) = 4 bytes for alignment
        opt_len += 4;
    }
    if seg.sack_permitted {
        opt_len += TCP_OPT_SACK_PERMITTED_LEN as usize;
    }
    if sack_n > 0 {
        // NOP + NOP + kind(1) + len(1) + 8*N
        opt_len += 2 + 2 + 8 * sack_n;
    }
    // Pad to 4-byte boundary
    let padded_opt_len = (opt_len + 3) & !3;
    let data_offset_words = ((TCP_HEADER_LEN + padded_opt_len) / 4) as u8;
    let tcp_len = TCP_HEADER_LEN + padded_opt_len + payload.len();
    if out.len() < tcp_len {
        return None;
    }

    let hdr = build_header(
        seg.tuple.local_port,
        seg.tuple.remote_port,
        seg.seq_num,
        seg.ack_num,
        seg.flags,
        seg.window_size,
        data_offset_words,
    );
    let _hdr_len = write_header(&hdr, out)?;

    let mut opt_cursor = TCP_HEADER_LEN;
    if has_mss {
        out[opt_cursor] = TCP_OPT_MSS;
        out[opt_cursor + 1] = TCP_OPT_MSS_LEN;
        out[opt_cursor + 2..opt_cursor + 4].copy_from_slice(&seg.mss.to_be_bytes());
        opt_cursor += 4;
    }
    if has_wscale {
        out[opt_cursor] = TCP_OPT_NOP;
        out[opt_cursor + 1] = TCP_OPT_WINDOW_SCALE;
        out[opt_cursor + 2] = TCP_OPT_WINDOW_SCALE_LEN;
        out[opt_cursor + 3] = seg.wscale;
        opt_cursor += 4;
    }
    if seg.sack_permitted {
        out[opt_cursor] = TCP_OPT_SACK_PERMITTED;
        out[opt_cursor + 1] = TCP_OPT_SACK_PERMITTED_LEN;
        opt_cursor += 2;
    }
    if sack_n > 0 {
        // Two NOP bytes for 4-byte alignment of the SACK block data.
        out[opt_cursor] = TCP_OPT_NOP;
        out[opt_cursor + 1] = TCP_OPT_NOP;
        opt_cursor += 2;
        out[opt_cursor] = TCP_OPT_SACK;
        out[opt_cursor + 1] = (2 + 8 * sack_n) as u8;
        opt_cursor += 2;
        for i in 0..sack_n {
            let (left, right) = seg.sack_blocks[i];
            out[opt_cursor..opt_cursor + 4].copy_from_slice(&left.to_be_bytes());
            out[opt_cursor + 4..opt_cursor + 8].copy_from_slice(&right.to_be_bytes());
            opt_cursor += 8;
        }
    }
    // Zero any padding
    while opt_cursor < TCP_HEADER_LEN + padded_opt_len {
        out[opt_cursor] = TCP_OPT_END;
        opt_cursor += 1;
    }

    let data_start = TCP_HEADER_LEN + padded_opt_len;
    out[data_start..data_start + payload.len()].copy_from_slice(payload);

    let checksum =
        super::checksum::tcp_checksum(seg.tuple.local_ip, seg.tuple.remote_ip, &out[..tcp_len]);
    out[16..18].copy_from_slice(&checksum.to_be_bytes());
    Some(tcp_len)
}

// -----------------------------------------------------------------------------
// SegmentBuilder — single source of truth for TcpOutSegment construction
// -----------------------------------------------------------------------------

/// Factory methods for [`TcpOutSegment`] construction.
///
/// Every outgoing segment the TCP state machine emits comes from one of
/// these.  The goal is **one place** where "what does an ACK look like?"
/// is answered, so that adding a new field to `TcpOutSegment` is a
/// single-line change.  All methods take explicit field values — there
/// are no methods that borrow a connection struct.
pub struct SegmentBuilder;

impl SegmentBuilder {
    /// RST with an explicit tuple and seq — used by abort paths and LISTEN
    /// ACK rejection.
    #[inline]
    pub fn bare_rst(tuple: TcpTuple, seq: u32) -> TcpOutSegment {
        TcpOutSegment {
            tuple,
            seq_num: seq,
            ack_num: 0,
            flags: TCP_FLAG_RST,
            window_size: 0,
            mss: 0,
            wscale: 255,
            sack_permitted: false,
            sack_blocks: [(0, 0); 4],
            sack_block_count: 0,
        }
    }

    /// RST in response to an unexpected incoming segment (no matching
    /// connection in the table).  Implements the classic RFC 793 §3.4
    /// "if RST not set, emit RST/RST-ACK" rule.
    #[inline]
    pub fn rst_for(hdr: &TcpHeader, local_ip: [u8; 4], remote_ip: [u8; 4]) -> TcpOutSegment {
        let (seq, ack, flags) = if hdr.is_ack() {
            (hdr.ack_num, 0u32, TCP_FLAG_RST)
        } else {
            let seg_len = if hdr.is_syn() { 1u32 } else { 0u32 };
            (
                0u32,
                hdr.seq_num.wrapping_add(seg_len),
                TCP_FLAG_RST | TCP_FLAG_ACK,
            )
        };
        TcpOutSegment {
            tuple: TcpTuple {
                local_ip,
                local_port: hdr.dst_port,
                remote_ip,
                remote_port: hdr.src_port,
            },
            seq_num: seq,
            ack_num: ack,
            flags,
            window_size: 0,
            mss: 0,
            wscale: 255,
            sack_permitted: false,
            sack_blocks: [(0, 0); 4],
            sack_block_count: 0,
        }
    }

    /// Active-open SYN (client side).  The wscale of `0` is normalized to
    /// the "don't include option" sentinel `255`.
    #[inline]
    pub fn active_syn(tuple: TcpTuple, iss: u32, wscale: u8) -> TcpOutSegment {
        TcpOutSegment {
            tuple,
            seq_num: iss,
            ack_num: 0,
            flags: TCP_FLAG_SYN,
            window_size: DEFAULT_WINDOW_SIZE,
            mss: DEFAULT_MSS,
            wscale: if wscale > 0 { wscale } else { 255 },
            sack_permitted: true,
            sack_blocks: [(0, 0); 4],
            sack_block_count: 0,
        }
    }

    // -------------------------------------------------------------------------
    // Canonical explicit-field constructors
    // -------------------------------------------------------------------------

    /// Plain ACK with explicit (tuple, seq, ack, window).
    #[inline]
    pub fn ack(tuple: TcpTuple, seq: u32, ack: u32, window: u16) -> TcpOutSegment {
        TcpOutSegment {
            tuple,
            seq_num: seq,
            ack_num: ack,
            flags: TCP_FLAG_ACK,
            window_size: window,
            mss: 0,
            wscale: 255,
            sack_permitted: false,
            sack_blocks: [(0, 0); 4],
            sack_block_count: 0,
        }
    }

    /// `FIN|ACK` with explicit fields.
    #[inline]
    pub fn fin_ack(tuple: TcpTuple, seq: u32, ack: u32, window: u16) -> TcpOutSegment {
        TcpOutSegment {
            tuple,
            seq_num: seq,
            ack_num: ack,
            flags: TCP_FLAG_FIN | TCP_FLAG_ACK,
            window_size: window,
            mss: 0,
            wscale: 255,
            sack_permitted: false,
            sack_blocks: [(0, 0); 4],
            sack_block_count: 0,
        }
    }

    /// `SYN|ACK` with explicit fields, typically emitted by a
    /// simultaneous-open transition or passive-open path.
    #[inline]
    pub fn syn_ack(tuple: TcpTuple, seq: u32, ack: u32, window: u16, mss: u16) -> TcpOutSegment {
        TcpOutSegment {
            tuple,
            seq_num: seq,
            ack_num: ack,
            flags: TCP_FLAG_SYN | TCP_FLAG_ACK,
            window_size: window,
            mss,
            wscale: 255,
            sack_permitted: false,
            sack_blocks: [(0, 0); 4],
            sack_block_count: 0,
        }
    }

    /// Data-carrying PSH+ACK segment.  Caller passes the sequence number of
    /// the first payload byte and the live recv-buffer window.
    #[inline]
    pub fn data_push(tuple: TcpTuple, seq: u32, ack: u32, window: u16) -> TcpOutSegment {
        TcpOutSegment {
            tuple,
            seq_num: seq,
            ack_num: ack,
            flags: TCP_FLAG_ACK | TCP_FLAG_PSH,
            window_size: window,
            mss: 0,
            wscale: 255,
            sack_permitted: false,
            sack_blocks: [(0, 0); 4],
            sack_block_count: 0,
        }
    }

    /// Keepalive probe: `seq = snd_una - 1` so the peer is forced to
    /// acknowledge its latest `rcv_nxt` without touching the data stream.
    #[inline]
    pub fn keepalive_probe(
        tuple: TcpTuple,
        snd_una: u32,
        rcv_nxt: u32,
        rcv_wnd: u16,
    ) -> TcpOutSegment {
        TcpOutSegment {
            tuple,
            seq_num: snd_una.wrapping_sub(1),
            ack_num: rcv_nxt,
            flags: TCP_FLAG_ACK,
            window_size: rcv_wnd,
            mss: 0,
            wscale: 255,
            sack_permitted: false,
            sack_blocks: [(0, 0); 4],
            sack_block_count: 0,
        }
    }
}
