//! Outgoing TCP segments and their wire-format serializer.
//!
//! The state machine emits [`TcpOutSegment`] values describing *what* should
//! go on the wire; [`write_tcp_segment`] turns one into the actual bytes
//! (header + options + payload + checksum).  Splitting construction from
//! serialization keeps the state handlers free of byte-order plumbing and
//! gives tests one place to inspect either half.
//!
//! The [`SegmentBuilder`] type lands in P2.1 and is currently a thin stub;
//! state handlers still construct `TcpOutSegment { ... }` directly.

use super::TcpTuple;
use super::header::{
    TCP_HEADER_LEN, TCP_OPT_END, TCP_OPT_MSS, TCP_OPT_MSS_LEN, TCP_OPT_NOP, TCP_OPT_WINDOW_SCALE,
    TCP_OPT_WINDOW_SCALE_LEN, build_header, write_header,
};

/// Outgoing segment generated by the state machine.
///
/// The TCP layer produces these; the network layer converts them to
/// wire-format packets via [`write_tcp_segment`] and hands them to the NIC.
#[derive(Clone, Copy, Debug)]
pub struct TcpOutSegment {
    pub tuple: TcpTuple,
    pub seq_num: u32,
    pub ack_num: u32,
    pub flags: u8,
    pub window_size: u16,
    /// MSS option to include (0 = no MSS option).
    pub mss: u16,
    /// Window Scale option shift count (255 = don't include option).
    pub wscale: u8,
}

/// Serialize a [`TcpOutSegment`] plus its payload into `out`.
///
/// Writes the TCP header, MSS / Window Scale options (if requested), payload
/// bytes, and finally patches the checksum field (bytes 16..18) with the
/// one's-complement sum over the pseudo-header plus the whole segment.
///
/// Returns the number of bytes written or `None` if `out` is too short.
pub fn write_tcp_segment(seg: &TcpOutSegment, payload: &[u8], out: &mut [u8]) -> Option<usize> {
    let has_mss = seg.mss != 0;
    let has_wscale = seg.wscale != 255;
    let mut opt_len = 0usize;
    if has_mss {
        opt_len += 4;
    }
    if has_wscale {
        // NOP + Window Scale (3 bytes) = 4 bytes for alignment
        opt_len += 4;
    }
    // Pad to 4-byte boundary
    let padded_opt_len = (opt_len + 3) & !3;
    let data_offset_words = ((TCP_HEADER_LEN + padded_opt_len) / 4) as u8;
    let tcp_len = TCP_HEADER_LEN + padded_opt_len + payload.len();
    if out.len() < tcp_len {
        return None;
    }

    let hdr = build_header(
        seg.tuple.local_port,
        seg.tuple.remote_port,
        seg.seq_num,
        seg.ack_num,
        seg.flags,
        seg.window_size,
        data_offset_words,
    );
    let _hdr_len = write_header(&hdr, out)?;

    let mut opt_cursor = TCP_HEADER_LEN;
    if has_mss {
        out[opt_cursor] = TCP_OPT_MSS;
        out[opt_cursor + 1] = TCP_OPT_MSS_LEN;
        out[opt_cursor + 2..opt_cursor + 4].copy_from_slice(&seg.mss.to_be_bytes());
        opt_cursor += 4;
    }
    if has_wscale {
        out[opt_cursor] = TCP_OPT_NOP;
        out[opt_cursor + 1] = TCP_OPT_WINDOW_SCALE;
        out[opt_cursor + 2] = TCP_OPT_WINDOW_SCALE_LEN;
        out[opt_cursor + 3] = seg.wscale;
        opt_cursor += 4;
    }
    // Zero any padding
    while opt_cursor < TCP_HEADER_LEN + padded_opt_len {
        out[opt_cursor] = TCP_OPT_END;
        opt_cursor += 1;
    }

    let data_start = TCP_HEADER_LEN + padded_opt_len;
    out[data_start..data_start + payload.len()].copy_from_slice(payload);

    let checksum =
        super::checksum::tcp_checksum(seg.tuple.local_ip, seg.tuple.remote_ip, &out[..tcp_len]);
    out[16..18].copy_from_slice(&checksum.to_be_bytes());
    Some(tcp_len)
}

// -----------------------------------------------------------------------------
// SegmentBuilder (stub; wired in P2.1)
// -----------------------------------------------------------------------------

/// Placeholder for the P2.1 [`SegmentBuilder`] helper.
///
/// The final shape replaces the ~27 inline `TcpOutSegment { ... }` constructions
/// scattered across the state handlers with fluent factory methods like
/// `SegmentBuilder::ack_of(&conn)` / `rst_for(hdr, local, remote)` / `fin_ack(&conn)`.
/// This stub exists so dependent modules can import the path without a later
/// circular-import shuffle.
pub struct SegmentBuilder;
