#!/usr/bin/env python3
import subprocess
import sys
from pathlib import Path


KERNEL_BASE = 0xFFFF_8000_0000_0000
TEXT_TYPES = set("tTwW")


def rust_string(value: str) -> str:
    out = ['"']
    for ch in value:
        code = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif 0x20 <= code <= 0x7E:
            out.append(ch)
        else:
            out.append(f"\\u{{{code:x}}}")
    out.append('"')
    return "".join(out)


def parse_nm(llvm_nm: str, elf: Path):
    proc = subprocess.run(
        [llvm_nm, "-n", "--defined-only", "--demangle", str(elf)],
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    )
    symbols = []
    seen = set()
    for line in proc.stdout.splitlines():
        parts = line.split(maxsplit=2)
        if len(parts) != 3:
            continue
        addr_s, typ, name = parts
        if len(typ) != 1 or typ not in TEXT_TYPES:
            continue
        try:
            addr = int(addr_s, 16)
        except ValueError:
            continue
        if addr < KERNEL_BASE:
            continue
        if not name or name.startswith(".L"):
            continue
        key = (addr, name)
        if key in seen:
            continue
        seen.add(key)
        symbols.append((addr, name))
    symbols.sort(key=lambda item: item[0])
    return symbols


def write_table(symbols, out: Path):
    with out.open("w", encoding="utf-8") as f:
        f.write("// Generated by scripts/gen_kernel_symbols.py.\n")
        f.write("pub static KERNEL_SYMBOLS: &[crate::ksym::KernelSymbol] = &[\n")
        for addr, name in symbols:
            f.write(
                "    crate::ksym::KernelSymbol { "
                f"addr: 0x{addr:016x}, name: {rust_string(name)}"
                " },\n"
            )
        f.write("];\n")


def main() -> int:
    if len(sys.argv) != 4:
        print(
            "usage: gen_kernel_symbols.py <llvm-nm> <kernel.elf> <out.rs>",
            file=sys.stderr,
        )
        return 2
    llvm_nm = sys.argv[1]
    elf = Path(sys.argv[2])
    out = Path(sys.argv[3])
    symbols = parse_nm(llvm_nm, elf)
    write_table(symbols, out)
    print(f"gen_kernel_symbols: wrote {len(symbols)} symbols to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
